name: Workflow with Email Identifier

on:
  # Runs when manually triggered
  workflow_dispatch:
  # Also runs on push to main branch
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 21f1000509@ds.study.iitm.ac.in
        run: echo "Hello, world!"
